### ISSUE TITLE
Feature: User can view the catalog page.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/The-Post-Party-Playground#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see the board game catalog page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to select the catalog button on the navbar and it will direct them to the catalog page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="616" alt="Screenshot 2023-04-17 at 10 16 31 AM" src="https://user-images.githubusercontent.com/122064415/232560919-ac622442-1363-40c1-a115-6637f8492bc9.png">
<img width="297" alt="Screenshot 2023-04-17 at 10 16 48 AM" src="https://user-images.githubusercontent.com/122064415/232560944-e373be54-1046-43d5-a314-b3e56741245f.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to have at least 6 games in total.

### ☁️ Server Tasks

- [x] Update `server.js` to be able to respond to the request of the client asking to see the board games that are in the database.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create all the necessary pages for routing.
- [x] Create all the necessary pages.
- [x] Set up the routing for each individual page.
- [x] Create a component for the header.
   - [x] Create a function for the title
- [x] Create a component for the footer.
- [x] Create a component that receives the response of the request and displays the board games on the catalog page.
- [x] Create the home page of the website.
   - [x] Create the carousel for the home page.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
