### ISSUE TITLE
Feature: User can edit account info

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/The-Post-Party-Playground#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able see their account info and change any information they desire.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on account and view their info. User can click the update button and change any fields they want to change and then confirm their update. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to have account info in orders table

### ☁️ Server Tasks

- [x] Update `server.js` to update "customerAccounts" table
- [x] Update the order middleware to copy the customer info into "orders" table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to show account info
- [x] Create a component to update the account info with a form

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
