### ISSUE TITLE
Feature: User can click on the product to see more information about it.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/The-Post-Party-Playground#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see detail information about a product.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will be able to click on the product. Once clicking the product, it will direct them to a page with more detail information about the product.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile view:
<img width="210" alt="Screenshot 2023-04-20 at 1 13 38 AM" src="https://user-images.githubusercontent.com/122064415/233303427-ce31fe3e-c0c1-409d-ac42-992868e674fa.png">

Desktop View
<img width="572" alt="Screenshot 2023-04-20 at 1 13 59 AM" src="https://user-images.githubusercontent.com/122064415/233303438-03fa1008-9ee8-4364-9f48-08d7d0748803.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Clean up database
    - [x] Delete thumb url

### ☁️ Server Tasks

- [x] Update `server.js` to retrieve information of a specific product based on their productId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display the product details page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
