### ISSUE TITLE
Feature: User can add a product to their shopping cart.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/The-Post-Party-Playground#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see the cart page and add a product to their cart page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can set quantity and add the product to their cart from the product details page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] None!

### ☁️ Server Tasks

- [x] Update `server.js` to get the product that are in the cart.
- [x] Update `server.js` to insert the product into the cart table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to add item to the cart
- [x] Create a component to render a cart page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
