### ISSUE TITLE
Feature: User can search for a board game through the database.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/The-Post-Party-Playground#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for products that are in the database.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to type in the name of the product and will see a dropdown results that match the name in the database. User can select the product in the drop down or search for it and will be sent to a results page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] None!

### ☁️ Server Tasks

- [x] Update `server.js` to have a get request that searches for similar product names.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to handle the search results.
- [x] Update search bar component.

### 🧑‍⚕️ Clean Up Tasks

 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
